### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by sailor-z** [GaodeRender/triangle-splatting#4]
Hi,

Thank you for the interesting work and for sharing the code. I encountered a "CUDA out of memory" error while running it. Please find the screenshot below:

![Image](https://github.com/user-attachments/assets/520dec9c-41fc-4895-b5d4-cda9324c8ed9)

I noticed that `self.scene_bbox` is `None`, and no points are sampled from outside. However, this doesn’t seem directly related to the memory issue. Could you please share some insights or suggestions on how to fix this issue?

Thanks in advance!

**Comment by GaodeRender** [comment]
Which version of torch are you using? Can you try the torch version listed in requirements.txt, i.e. torch==2.5.1 ?
Older version pytorch use a different tensor broadcasting logic and can cause unexpected tensor expansion, which could be the cause of this huge amount of CUDA memory allocation.
Besides, initializing the model with 25M points could cause a large memory usage (although certainly not as large as 131069GB). It is recommended to change the sampling method from direct to random or grid and set the n_sample_inside parameter a lower amount in the config file.

**Comment by sailor-z** [comment]
Thanks for the prompt reply. I followed the instructions to setup the environment, so the pytorch version matches the one listed.  I also tried a sparser point cloud, but the problem still existed.

**Comment by GaodeRender** [comment]
can you also show your CUDA and driver version?

**Comment by sailor-z** [comment]
Thanks a lot. It works now!

I got nothing when running `echo ${TORCH_CUDA_ARCH_LIST}`. I solved the problem by manually setting `export TORCH_CUDA_ARCH_LIST ="7.0"` and then executing `pip install . --no-cache-dir`.
